status is-interactive; and begin
  # keep-sorted start
  abbr -c docker attach 'container attach'
  abbr -c docker build 'image build'
  abbr -c docker commit 'container commit'
  abbr -c docker cp 'container cp'
  abbr -c docker create 'container create'
  abbr -c docker diff 'container diff'
  abbr -c docker events 'system events'
  abbr -c docker exec 'container exec'
  abbr -c docker export 'container export'
  abbr -c docker history 'image history'
  abbr -c docker images 'image list'
  abbr -c docker import 'image import'
  abbr -c docker info 'system info'
  abbr -c docker kill 'container kill'
  abbr -c docker load 'image load'
  abbr -c docker logs 'container logs'
  abbr -c docker pause 'container pause'
  abbr -c docker port 'container port'
  abbr -c docker ps 'container ps'
  abbr -c docker pull 'image pull'
  abbr -c docker push 'image push'
  abbr -c docker rename 'container rename'
  abbr -c docker restart 'container restart'
  abbr -c docker rm 'container rm'
  abbr -c docker rmi 'image rm'
  abbr -c docker run 'container run'
  abbr -c docker save 'image save'
  abbr -c docker start 'container start'
  abbr -c docker stats 'container stats'
  abbr -c docker stop 'container stop'
  abbr -c docker tag 'image tag'
  abbr -c docker top 'container top'
  abbr -c docker unpause 'container unpause'
  abbr -c docker update 'container update'
  abbr -c docker wait 'container wait'
  # keep-sorted end
end
